# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: b/b.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tb/b.proto\x12\x01\x62\"\x18\n\x08MessageB\x12\x0c\n\x04Name\x18\x01 \x01(\tB\x1fZ\x1dpurzelweter/python-protobuf/bb\x06proto3')



_MESSAGEB = DESCRIPTOR.message_types_by_name['MessageB']
MessageB = _reflection.GeneratedProtocolMessageType('MessageB', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEB,
  '__module__' : 'b.b_pb2'
  # @@protoc_insertion_point(class_scope:b.MessageB)
  })
_sym_db.RegisterMessage(MessageB)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035purzelweter/python-protobuf/b'
  _MESSAGEB._serialized_start=16
  _MESSAGEB._serialized_end=40
# @@protoc_insertion_point(module_scope)
