// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: root.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RootServiceClient is the client API for RootService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RootServiceClient interface {
	// Greeting greets the request and returns the current time.
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type rootServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRootServiceClient(cc grpc.ClientConnInterface) RootServiceClient {
	return &rootServiceClient{cc}
}

func (c *rootServiceClient) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/root.RootService/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootServiceServer is the server API for RootService service.
// All implementations must embed UnimplementedRootServiceServer
// for forward compatibility
type RootServiceServer interface {
	// Greeting greets the request and returns the current time.
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
	mustEmbedUnimplementedRootServiceServer()
}

// UnimplementedRootServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRootServiceServer struct {
}

func (UnimplementedRootServiceServer) Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}
func (UnimplementedRootServiceServer) mustEmbedUnimplementedRootServiceServer() {}

// UnsafeRootServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RootServiceServer will
// result in compilation errors.
type UnsafeRootServiceServer interface {
	mustEmbedUnimplementedRootServiceServer()
}

func RegisterRootServiceServer(s grpc.ServiceRegistrar, srv RootServiceServer) {
	s.RegisterService(&RootService_ServiceDesc, srv)
}

func _RootService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/root.RootService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServiceServer).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RootService_ServiceDesc is the grpc.ServiceDesc for RootService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RootService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "root.RootService",
	HandlerType: (*RootServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _RootService_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "root.proto",
}
