# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: root.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroot.proto\"\x1b\n\x0bMessageRoot\x12\x0c\n\x04Name\x18\x01 \x01(\tb\x06proto3')



_MESSAGEROOT = DESCRIPTOR.message_types_by_name['MessageRoot']
MessageRoot = _reflection.GeneratedProtocolMessageType('MessageRoot', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEROOT,
  '__module__' : 'root_pb2'
  # @@protoc_insertion_point(class_scope:MessageRoot)
  })
_sym_db.RegisterMessage(MessageRoot)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEROOT._serialized_start=14
  _MESSAGEROOT._serialized_end=41
# @@protoc_insertion_point(module_scope)
