# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: root.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from a import a_pb2 as a_dot_a__pb2
from b import b_pb2 as b_dot_b__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroot.proto\x12\x04root\x1a\ta/a.proto\x1a\tb/b.proto\"Q\n\x0fGreetingRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x17\n\x02MA\x18\x02 \x01(\x0b\x32\x0b.a.MessageA\x12\x17\n\x02MB\x18\x03 \x01(\x0b\x32\x0b.b.MessageB\"%\n\x10GreetingResponse\x12\x11\n\tGreetedAt\x18\x01 \x01(\t2H\n\x0bRootService\x12\x39\n\x08Greeting\x12\x15.root.GreetingRequest\x1a\x16.root.GreetingResponseB%Z purzelweter/python-protobuf/main\x90\x01\x01\x62\x06proto3')



_GREETINGREQUEST = DESCRIPTOR.message_types_by_name['GreetingRequest']
_GREETINGRESPONSE = DESCRIPTOR.message_types_by_name['GreetingResponse']
GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGREQUEST,
  '__module__' : 'root_pb2'
  # @@protoc_insertion_point(class_scope:root.GreetingRequest)
  })
_sym_db.RegisterMessage(GreetingRequest)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGRESPONSE,
  '__module__' : 'root_pb2'
  # @@protoc_insertion_point(class_scope:root.GreetingResponse)
  })
_sym_db.RegisterMessage(GreetingResponse)

_ROOTSERVICE = DESCRIPTOR.services_by_name['RootService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z purzelweter/python-protobuf/main\220\001\001'
  _GREETINGREQUEST._serialized_start=42
  _GREETINGREQUEST._serialized_end=123
  _GREETINGRESPONSE._serialized_start=125
  _GREETINGRESPONSE._serialized_end=162
  _ROOTSERVICE._serialized_start=164
  _ROOTSERVICE._serialized_end=236
RootService = service_reflection.GeneratedServiceType('RootService', (_service.Service,), dict(
  DESCRIPTOR = _ROOTSERVICE,
  __module__ = 'root_pb2'
  ))

RootService_Stub = service_reflection.GeneratedServiceStubType('RootService_Stub', (RootService,), dict(
  DESCRIPTOR = _ROOTSERVICE,
  __module__ = 'root_pb2'
  ))


# @@protoc_insertion_point(module_scope)
