# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a/a.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ta/a.proto\"\x18\n\x08MessageA\x12\x0c\n\x04Name\x18\x01 \x01(\tb\x06proto3')



_MESSAGEA = DESCRIPTOR.message_types_by_name['MessageA']
MessageA = _reflection.GeneratedProtocolMessageType('MessageA', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEA,
  '__module__' : 'a.a_pb2'
  # @@protoc_insertion_point(class_scope:MessageA)
  })
_sym_db.RegisterMessage(MessageA)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEA._serialized_start=13
  _MESSAGEA._serialized_end=37
# @@protoc_insertion_point(module_scope)
